### ISSUE TITLE
Tracking issue: more test cases

### ISSUE THREAD

**Issue by tchataigner** [argumentcomputer/zk-light-clients#9]
We iterated over the light client on happy path and testing over valid data. We now need to add more test cases to our code to ensure it's proper behavior in all cases.

_To evolve along development_

- [ ] Emulate state transition from genesis to epoch 4 with data being valid
- [ ] Receiving a dishonest proof of epoch transition (eg: wrong signature, past epoch ...)
- [ ] Receiving a dishonest sparse merkle proof
- [ ] `EpochChangeProof` and `LedgerInfoWithSignatures` that skip an epoch
